### ISSUE TITLE
Does Emcee generate a XCResult file

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [avito-tech/Emcee#18]
Hi, I was wondering does Emcee generate an XCResult file after all the tests have been executed or create a report that links the logs to screenshots similar to https://github.com/TitouanVanBelle/XCTestHTMLReport ?

**Comment by beefon** [comment]
Hi, Emcee currently does not generate anything except Junit. Also, it does not provide any artifacts to plugins, although it could do that. I can guide you through a plan on how that can be implemented. Then, plugins will receive paths to `xcresult` files and will be able to process them as needed (merge/upload/generate XCTestHTMLReport).

**Comment by Ashraf-Ali-aa** [comment]
@beefon that would be very useful, just wondering would it be possible to create a diagram of how Emcee works simualr to this https://github.com/Subito-it/Mendoza/blob/master/md/under-the-hood.md so that its alot easier to understand the inner workings of Emcee. thanks

**Comment by beefon** [comment]
There are couple of problems we need to take care of. First of all, Emcee uses `xcodebuild`, but does not parse its output correctly. 

- Emcee must adopt `-resultBundlePath /path/to/output.xcresult` flag in order to make `xcodebuild` not spam into temp folders in derived data.

- Then, Emcee should pass `-resultStreamPath /path/to/jsonstream.json`. This is a JSON file that `xcodebuild` can stream its event into. Emcee must parse all needed info from there "on the fly". The events contain info about when test starts, finishes, errors, etc. Currently this is done in an ugly way [via regexp](https://github.com/avito-tech/Emcee/blob/master/Sources/AppleTools/RegexLogParser.swift). This leads to sometimes false results (e.g. test failure text won't be captured), but quite rare though.

After this will be done, Emcee will have a control where `xcresult` of each `xcodebuild` invocation will be stored. Then, Emcee can start pushing these files to its plugins. I guess this can be done via additional field(s) in `TestRunResult` model. Plugins will be able to pick up paths to `xcresult` files and process them.

---------------

Regards the diagram, thanks for suggestion. We will try to come up with somthing.

**Comment by beefon** [comment]
#21 added an ability to access `xcresult` bundle from the plugins.

**Comment by beefon** [comment]
FWIW, v14 allows to work with xcresults, and there is also an Allure plugin.

Read more here: https://github.com/avito-tech/Emcee/releases/tag/14.0.0
