### ISSUE TITLE
Устаревшая документация

### ISSUE THREAD

**Issue by Gremlinok** [avito-tech/Emcee#7]
Добрый день!

Хотелось бы попробовать ваше решение у себя на проекте, но, к сожалению, не удаётся запустить утилиту даже на вашем тестовом приложении TestApp.

Вся информация, которая доступна в репозитории не даёт возможности разобраться в возможных решениях возникших проблем, а единственное, что удаётся достать из логов это (1ый лог из консоли, 2ой — из файла "...fbxctest_stderr.txt"):

1. Failed to get runtime dump, error: Runtime dump did not create a JSON file at expected location: "путь до runtime_tests.json"
2. {"code":0,"errorOrigin":"FBXCTestError","domain":"com.facebook.FBTestError","text":"A shim directory was searched for at '\/Users\/%username%\/Library\/Caches\/ru.avito.Runner.cache\/ffd7ec1497eab3856d6015477c0b99cd6a96c4340e33feb564c3f2ed7cdf210b\/lib', but it was not there"}

Буду благодарен, если вы актуализируете документацию или простой гайд по запуску вашей утилиты на вашем тестовом проекте TestApp.

Спасибо!

**Comment by beefon** [comment]
Thanks for your report, we will update the docs and will let you know as soon as they are ready.

**Comment by olyv** [comment]
Is it going to work on MacOS Mojave? `make build` fails for me because of ZIPFoundation dependency ("error: the product 'ZIPFoundation' requires minimum platform version 10.11 for macos platform").

As for "`AvitoRunner [subcommand] --help` will print the argument list for each subcommand." -- how do I install AvitoRunner to make it available as via cli?

Thanks.

**Comment by beefon** [comment]
Hello, currently Emcee can only be built using Xcode 10.1 unfortunately. This is due to package.swift maintenance hell - otherwise we'd have to ship 2 versions of that file and maintain both and it will be hard and error prone. 

We are planning to upgrade it to Swift 5 as soon as we migrate away from libSPM and switch to our ArgLib for argument parsing. I will let you know as soon as this happens. Meanwhile, you could try to use a prebuilt binary.

[AvitoRunner.artifact.zip](https://github.com/avito-tech/Emcee/files/3382281/AvitoRunner.artifact.zip)

**Comment by olyv** [comment]
Hi @beefon, thank you for quick response. I just tried that prebuilt binary and received exactly the same error as OP described. I assumed that I missed some dependencies from fbsimctl but couldn't install fbsimctl and Facebook recommends using idb (https://github.com/facebook/idb/issues/503) instead. Not sure what I am doing wrong, maybe missing some setup?

**Comment by beefon** [comment]
@olyv if you could please share your output I'll be glad to investigate further.

**Comment by zhelanov** [comment]
According to readme I need to provide path to "queue-server-run-configuration" file but I can't find an example of it. Can you add it to the project readme or point to a place where I can find it?
Thanks in advance!

**Comment by beefon** [comment]
I've started a Wiki:

https://github.com/avito-tech/Emcee/wiki

I will keep populating it.
